---
title: "GWR and Mixed GWR with spatial autocorrelation"
author: "Ghislain Geniaux"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    keep_md: false
vignette: >
  %\VignetteIndexEntry{GWR and Mixed GWR with spatial autocorrelation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
target_url <- "https://ggeniaux.github.io/mgwrsar_vignettes/GWR-and-Mixed-GWR-with-spatial-autocorrelation.html"
```

This vignette is hosted online due to size and computational constraints.

**Online version:** <https://ggeniaux.github.io/mgwrsar_vignettes/GWR-and-Mixed-GWR-with-spatial-autocorrelation.html>

```{r redirect, echo=FALSE, results='asis'}
cat(sprintf(
  '<p><strong>Online version:</strong> <a href="%s">%s</a></p>',
  target_url, target_url
))

# Meta refresh (works without JS); short delay to keep the page readable
cat(sprintf('<meta http-equiv="refresh" content="3; url=%s">', target_url))

# JS redirect as a fallback
cat(sprintf("<script>setTimeout(function(){ window.location.href = '%s'; }, 3000);</script>", target_url))
```
