// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gwr_beta_univar_cpp
Rcpp::List gwr_beta_univar_cpp(const Rcpp::NumericVector& y, const Rcpp::NumericVector& x, const Rcpp::NumericMatrix& XV, const Rcpp::IntegerMatrix& indexG, const Rcpp::NumericMatrix& Wd, const Rcpp::IntegerVector& TP, bool get_ts, bool get_s, bool get_se);
RcppExport SEXP _mgwrsar_gwr_beta_univar_cpp(SEXP ySEXP, SEXP xSEXP, SEXP XVSEXP, SEXP indexGSEXP, SEXP WdSEXP, SEXP TPSEXP, SEXP get_tsSEXP, SEXP get_sSEXP, SEXP get_seSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type XV(XVSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type indexG(indexGSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Wd(WdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type TP(TPSEXP);
    Rcpp::traits::input_parameter< bool >::type get_ts(get_tsSEXP);
    Rcpp::traits::input_parameter< bool >::type get_s(get_sSEXP);
    Rcpp::traits::input_parameter< bool >::type get_se(get_seSEXP);
    rcpp_result_gen = Rcpp::wrap(gwr_beta_univar_cpp(y, x, XV, indexG, Wd, TP, get_ts, get_s, get_se));
    return rcpp_result_gen;
END_RCPP
}
