# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gwr_beta_univar_cpp <- function(y, x, XV, indexG, Wd, TP, get_ts, get_s, get_se) {
    .Call(`_mgwrsar_gwr_beta_univar_cpp`, y, x, XV, indexG, Wd, TP, get_ts, get_s, get_se)
}

